CREATE DATABASE ABD_03361_A_MAURO_MASSAO;

USE ABD_03361_A_MAURO_MASSAO;

CREATE TABLE FAMILIA (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
PARENTESCO VARCHAR(50) NOT NULL,
IDADE INT,
CIDADE VARCHAR(50)
);

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ('Massako Sakai', 'Mãe', 77, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ('Júlio Sakai', 'Pai', 79, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ('Mônica Mayumi', 'Irmã', 50, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ('Kevin Sakai', 'Sobrinho', 21, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ('Lucinda ALves', 'Esposa', 51, 'São Paulo');

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ('Thayna Akemi', 'Filha', 17, 'São Paulo');